language: python
python:
  - '2.7'
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
sudo: required
dist: trusty
services:
  - docker
install:
  - source cfg4dev
script:
  - pep8
  - flake8
  - shellcheck $(find . -name \*.sh)
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-image.sh -t "$TRAVIS_TAG" $DOCKER_USERNAME $DOCKER_PASSWORD; fi
