language: python
python:
  - '2.7'
sudo: required
dist: trusty
services:
  - docker
install:
  - source cfg4dev
script:
  - pep8
  - flake8
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-image.sh -v -t "$TRAVIS_TAG" $DOCKER_USERNAME $DOCKER_PASSWORD; fi
