language: python
python:
  - '2.7'
sudo: required
dist: trusty
services:
  - docker
env:
  - DOCKER_TEMP_TAG=bindle
install:
  - source cfg4dev
  - docker pull koalaman/shellcheck:latest
script:
  - run_pip_check.sh
  - run_flake8.sh
  - run_shellcheck.sh -v
  - run_repo_security_scanner.sh
  - travis_fold start "build.python.packages"
  - python setup.py bdist_wheel sdist --formats=gztar
  - travis_fold end "build.python.packages"
  - travis_fold start "build.docker.images"
  - ./dockerfiles/build-docker-image.sh "$DOCKER_USERNAME" "$DOCKER_TEMP_TAG" ./dist/analyze-restful-api-load-test-results-*.*.*.tar.gz
  - travis_fold end "build.docker.images"
  - tests/integration/docker_image_integration_tests.sh "$DOCKER_USERNAME/analyze-restful-api-load-test-results:$DOCKER_TEMP_TAG"
deploy:
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh $DOCKER_USERNAME $DOCKER_PASSWORD $DOCKER_TEMP_TAG latest
    on:
      branch: master
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh $DOCKER_USERNAME $DOCKER_PASSWORD $DOCKER_TEMP_TAG $TRAVIS_TAG
    on:
      tags: true
